npm -i
cd edu-frontend
npm -i
npm run dev
node -v
cd edu-frontend
node -v
cd edu-frontend
npm -i
npm run dev
cd edu-frontend
cd edu-frontend
node -v
npm -i
npm run dev
cd edu-frontend
npm -i
 /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/jdt.ls-java-project/bin CarSale 
 /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin SortThreeDigitNumber 
 /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
 cd /Users/macbookpro/Desktop/java ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/macbookpro/Library/Application\ Support/Code/User/workspaceStorage/10c4f0baa193148255fd1be8a34c7571/redhat.java/jdt_ws/java_469c439/bin Solution 
